name: Deploy v3

on:
  workflow_dispatch:

jobs:

  deploy_dev:
    name: Deploy MyTestApp Dev
    uses: ./.github/workflows/deploy_service.yml
    with:
      deploy_env: dev
      service_name: MyTestApp
      service_url: "http://dev.MyTestApp.com"
      approval_environment: no_approval
      app_sha: ${{ github.head_ref }}

  deploy_stage:
    name: Deploy MyTestApp Stage
    needs: [deploy_dev]
    uses: ./.github/workflows/deploy_service.yml
    with:
      deploy_env: stage
      service_name: MyTestApp
      service_url: "http://stage.MyTestApp.com"
      approval_environment: dev_approval
      app_sha: ${{ github.head_ref }}

  deploy_prod:
    name: Deploy MyTestApp Production
    needs: [deploy_stage]
    uses: ./.github/workflows/deploy_service.yml
    with:
      deploy_env: production
      service_name: MyTestApp
      service_url: "http://prod.MyTestApp.com"
      approval_environment: qa_approval
      app_sha: ${{ github.head_ref }}

