name: Update Release Draft

on:
  workflow_dispatch:

jobs:

  draft_release:
    name: Update Release Notes
    runs-on: ubuntu-latest
    steps:
      - id: short_sha
        run: echo "short_sha=`echo ${{ github.sha }} | cut -c 1-7`" >> $GITHUB_ENV

      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        # with:
        #   config-name: my-config.yml
        #   disable-autolabeler: true
        with:
          name: ${{ env.short_sha }}
          tag: 'master-${{ env.short_sha }}'
          version: ${{ env.short_sha }}
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
