# This is a basic workflow to help you get started with Actions

name: Update Release Draft

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  tag_commit_on_master:
    name: Tag Commit on Master
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Check Out Base
        id: base_checkout
        uses: actions/checkout@v2

      - id: short_sha
        run: echo "short_sha=`echo ${{ github.sha }} | cut -c 1-7`" >> $GITHUB_ENV

      - name: Apply Tag of Commit Hash to Master
        id: tag_master_with_commit
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.short_sha }}
          tag_prefix: 'master-'


  draft_release:
    name: Update Release Notes
    runs-on: ubuntu-latest
    steps:
      - id: short_sha
        run: echo "short_sha=`echo ${{ github.sha }} | cut -c 1-7`" >> $GITHUB_ENV

      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        # with:
        #   config-name: my-config.yml
        #   disable-autolabeler: true
        with:
          name: ${{ env.short_sha }}
          tag: 'master-${{ env.short_sha }}'
          version: ${{ env.short_sha }}
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
