name: Publish Release

on:
  workflow_dispatch:

jobs:

  publish_release:
    name: Publish Release Notes
    runs-on: ubuntu-latest
    steps:
      - id: short_sha
        run: echo "short_sha=`echo ${{ github.sha }} | cut -c 1-7`" >> $GITHUB_ENV

      - uses: release-drafter/release-drafter@v5
        with:
          name: ${{ env.short_sha }}
          tag: 'master-${{ env.short_sha }}'
          version: ${{ env.short_sha }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
