name: Tag master branch

on:
  push:
    branches:
      - master

jobs:

  tag_commit_on_master:
    name: Tag Commit on Master
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Check Out Base
        id: base_checkout
        uses: actions/checkout@v2

      - id: short_sha
        run: echo "short_sha=`echo ${{ github.sha }} | cut -c 1-7`" >> $GITHUB_ENV

      - name: Apply Tag of Commit Hash to Master
        id: tag_master_with_commit
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.short_sha }}
          tag_prefix: 'master-'
